name: Build
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  test-build:
    env:
      PROJECT_PATH: "scriptmod/uwp.Unofficial_Webfishing_Patch.csproj"
    runs-on: ubuntu-latest
    steps:
      # - name: Install PowerShell
      #   uses: PSModule/install-powershell@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Install Godot
        uses: u-w-p/Setup-Godot@v2
        with:
          godot-version: 3.5.2

      - uses: actions/checkout@v5

      - name: Build PCK
        run: |
          cp gd
          godot --export "uwp" uwp.pck

      - name: Install .Net dependencies (1/2)
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Install .Net dependencies (2/2)
        run: |
          curl -L -o gdw.zip https://github.com/NotNite/GDWeave/releases/download/v2.0.14/GDWeave.zip
          mkdir lib && unzip gdw.zip -d ./lib

      - name: Build DLL
        run: |
          export GDWeavePath="$(pwd)/lib/GDWeave"
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
